name: CI

on: [push, pull_request]

jobs:
  test-revoize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pipx
        run: |
          sudo apt-get update
          sudo apt-get install -y pipx
          pipx ensurepath
          export PATH=/root/.local/bin:$PATH
      - name: Install Pyenv and Python
        run: |
          curl https://pyenv.run | bash
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          pyenv install $(cat .python-version)
      - name: Install Poetry and Poe
        run: |
          pipx install poetry
          poetry config virtualenvs.prefer-active-python true
          pipx install poethepoet
      - name: Install Dependencies
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          poetry config virtualenvs.prefer-active-python true
          poetry install
      - name: Test
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          poetry config virtualenvs.prefer-active-python true
          poe test
